safe: false

# build settings
markdown: kramdown
highlighter: rouge
lsi: false
permalink: /:title

title: "Caleb"
description: "Find my projects"
baseurl: ""
url: "http://himsel.me" # replace by the correct url later
twitter_username: baudjules
github_username:  jbaud # (for now)
accent: "#f7f7ff" # accent color for blog column

author: "Caleb"
address: "street, <br> City, IL, USA"
email: "your@email.com" # replace

# google analytics tracking code
# if you want some stats
g_analytics: ""

# language settings
isolang: en

# exclude files
exclude:
  - LICENSE
  - README.md
